[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
runner = "qemu-system-riscv32 -machine sifive_e,revb=true -nographic -semihosting-config enable=on,target=native -kernel" # QEMU
# runner = "qemu-system-riscv32 -machine sifive_e,revb=true -nographic -semihosting-config enable=on,target=native -qtest tcp:localhost:3333 -kernel" # QTest
# runner = "riscv64-unknown-elf-gdb -q -x gdb_init" # OpenOCD
rustflags = [
    "-C", "link-arg=-Thifive1-link.x",
    "--cfg", "portable_atomic_target_feature=\"zaamo\"",
]

[env]
RISCV_RT_BASE_ISA = "rv32i"

[build]
target = "riscv32imc-unknown-none-elf"
